FROM python:3.11

# Встановлюємо системні залежності (і залишаємо кеш!)
RUN apt-get update && apt-get install -y \
    build-essential \
    git curl wget ca-certificates \
    ffmpeg \
    libglib2.0-0 libsm6 libxrender1 libxext6 libgl1 \
    && echo "Keeping APT cache for FAT image"

WORKDIR /app

# Копіюємо усі файли (включно з model.pt, inference.py та requirements.txt)
COPY . /app/

# Встановлюємо Python-бібліотеки (без --no-cache-dir, щоб збільшити шар)
RUN pip install --upgrade pip \
 && pip install -r requirements.txt

ENTRYPOINT ["python", "inference.py"]

